### ISSUE TITLE
Speeches don't show up in the search

### ISSUE THREAD

**Issue by JoelleSciboz** [dag-hammarskjold-library/dlx-rest#1121]
A/C.1/77/PV.1 speeches don't show up in the speeches search
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/9261460/64fcadd5-84eb-4655-b718-f098b04dd033)

**Comment by grozdanic** [comment]
There needs to be * at the end of the symbol  .. 089:'B22' AND symbol:A/C.1/77/PV.1* ;  this takes place when you enter just the symbol .. A/C.1/77/PV.1 to search ;  but yes this should be addressed in the app

**Comment by wernerval** [comment]
If I add the * in the browsing search it still doesn't show up:
<img width="654" alt="image" src="https://github.com/dag-hammarskjold-library/dlx-rest/assets/115169780/b680f92e-cdf5-48e5-baeb-09726f1d713f">

**Comment by viola-v** [comment]
This seems to be fixed.
